USE [TEConstruye]
GO




 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ACCESORIOS PARA BAÑO ' ,5681 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ACCESORIOS PARA BAÑO ESPECIAL ' ,5681 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ACEITE ' ,833 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ACIDO MURIÁTICO ' ,1569 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADAPTADOR  100MM HEMBRA PVC POTABLE ' ,2894 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADITIVO  ACELERANTE DE FRAGUA NORMAL ' ,2211 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADITIVO  REDUCTOR DE AGUA ' ,1087 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADITIVO IMPERMEABILIZANTE ' ,1937 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADITIVO REDUCTOR AGUA-RETARDAD,, ' ,1274 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADOQUIN 10X20X8 CMS ' ,3428 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADOQUIN 24X22X8 CMS ' ,3428 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALAMBRE DE AMARRE #16 ' ,639 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALAMBRE GALVANIZADO NO 16 ' ,849 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALFAJILLA SEMIDURA SIN CEPILLO 50X100 MM ' ,1059 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALFARJIA 2"X6" ' ,1491 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALFOMBRAS ' ,14838 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ANG 6X50X50X6M CALIENTE ' ,18615 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' APAGADOR NO 52 SUP, ' ,870 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' APAGADOR NO 54 DOBLE SUP ' ,735 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' APLANADORA 210-A BUF-BOMA ' ,22115 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' APTOS HASTA 12 EQUIPO BOMBEO ' ,269323 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARENA DE RÍO ' ,15990 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARTESONADO 50X1,25X3,34 ' ,11394 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARTESONADO SEMIDURO 50X1 50X3 34 M ' ,8136 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BAJANTE HG 26 /30 CM (12") ' ,2071 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BAJANTE HG CANOA 2X4 PULG ' ,2071 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BAJANTE HG NO 28/ 1 83 M ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA  CARGADOR 1 5 MT ' ,3868 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA  CARGADOR 1 75 MT ' ,4837 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA BANQUINA 1 50 MT ' ,5852 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA BANQUINA 1 75 MT ' ,6272 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA  1 95X50 MT ' ,6080 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 0 45XO 5 MT ' ,1538 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 0 75X0 5 MT ' ,2486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 0X0 5 MT ' ,3413 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 25X0 5 MT ' ,4164 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 37X0 5 MT ' ,4754 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 45X0 5 MT ' ,4961 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 5X0 5 MT ' ,4775 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 1 75X0 5 MT ' ,6039 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BALDOSA PREFA 4CM X 50CM ' ,6417 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BARANDAS Y PASAMANOS ' ,1600 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BASA DE CONCRETO 40 CM ' ,934 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BASE PARA MEDIDOR USA ' ,35866 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BATIDORA ' ,3278 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BATIDORA 3 5 M3/HR ' ,25186 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BATIENTE LAUREL LISA 12X25MM ' ,113 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BIDET PLAZA LOZA BLANCA ' ,94009 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BIDET RENAISSANCE LOZA BLANCA ' ,75125 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BISAGRA ,75X,75 HIERRO ' ,409 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BLOQUE 10*20*40 ' ,273 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BLOQUE 12*20*40 ' ,294 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BLOQUE 15X20X40 ' ,386 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BLOQUE CONCRETO 20X20X40 CMS ' ,486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BLOQUE TIPO A ' ,3470 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA AGUAS NEGRAS 0,5 HP RJSE55 ' ,308168 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA AGUAS NEGRAS 0,75 HP RJSE75 ' ,427292 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CENTRÍFUGA  3HP HI 300SPHE MONO ' ,409164 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CENTRÍFUGA 2 HP HI 200RSP MONO ' ,212351 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CENTRÍFUGA 3 HP 300SPHE TRI ' ,367730 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CENTRÍFUGA 5 HP 500 SPHE MONO ' ,538647 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CENTRÍFUGA PARA AGUA ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA CON TANQUE HIDRONEUMATICO ' ,818329 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA RED JACKET 0,5 HP HF 502SWC ' ,124303 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA RED JACKET 0,5 HP HF 50RJ ' ,129482 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA RED JACKET 1 HP HF 1002SWC ' ,147610 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA RED JACKET 1,5 HP HI 1502SWC ' ,170916 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA RED JACKET 1HP HF 100RJ ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 0,5 HP 10 GPM ' ,222709 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 1 HP 22 GPM ' ,282271 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 2 HP 28 GPM ' ,429881 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 3 HP 18 GPM ' ,631874 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 5 HP 50 GPM ' ,880481 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBA SUMERGIBLE 5 HP 55 GPM ' ,906377 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBEO CONCRETO ' ,4143 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOTAG LIMAT LIMAH CUMB, ' ,3262 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BREACKER 1 X 015 AMP ' ,2931 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BREACKER 1 X 020 AMP ' ,2931 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BREACKER 1 X 040 AMP ' ,3623 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BREACKER 2 X 040 AMP ' ,8408 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BROCHAS ' ,2127 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BROCHAS ' ,2127 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABEZOTE DE HIDRANTE ' ,139841 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN/THW NGM , 14 ' ,239 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN/THW NGM, 10 ' ,538 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN/THW NGM, 12 ' ,322 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE TW/ THW NO 6 ' ,517 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE TW/THW NO 8 ' ,310 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CACHERA ' ,40373 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CACHERA ' ,40373 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CACHERA FREGADERO ' ,30228 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CACHERA PARA BAÑO ' ,45448 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CACHERA PARA FREGADERO METAL SENCILLA ' ,30228 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CADENILLO 2"X4" ' ,1059 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CADENILLO 2"X6" ' ,1491 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAJA COND, RECTANGULAR ' ,173 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAJAS MEDIDORES AGUA POTABLE ' ,4661 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAL FINA ' ,39 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CALENTADOR AGUA (40 GLS) ' ,105800 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAMION ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAMIÓN  20 TONELADAS ' ,8804 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANALETA ESTRUCTURAL 0 74X4 57 NO 26 ' ,6266 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANALETA ESTRUCTURAL 0 74X6 10 NO 26 ' ,8338 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANALETA ESTRUCTURAL 0 74X7 01 NO 26 ' ,9581 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANALETA ESTRUCTURAL 0 74X7 62 NO 26 ' ,10410 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANOA HG 26/ 30 CM  (12") ' ,4402 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CANOAS Y BAJANTES INSTALADOS ' ,5697 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CARRETILLO FERRO LLANTA DE HULE ' ,19000 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CARRETILLOS ' ,103 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CELOSIAS COLOCADAS ' ,34183 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CEMENTO ' ,4331 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CENICERO 10CM ALCARRAZA ' ,3368 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CENTRAL HASTA 24 ABONADOS, 8 TRONCALES ' ,5627309 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CENTRO DE CARGA 6F EMBUTIR ' ,16791 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERAMICA 33X33 CMS ' ,2339 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERRADURA  ESPECIAL ' ,16314 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERRADURA BOTON ESPECIAL ' ,9581 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERRADURA CORRIENTE ' ,10358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERRADURA CORRIENTE ' ,21235 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERRADURA ESPECIAL ' ,36255 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CIELOS DE GYPSUM ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVO DE 38MM ACERO ' ,11 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVO PARA TECHO 63MM ' ,1219 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVOS 100 MM (4") ' ,779 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVOS DE 1 1/2" ' ,870 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVOS DE 1" C/CABEZA ' ,1010 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVOS DE 65 MM (2 1/2") ' ,620 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLOSET ' ,119123 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 100MM*45 PVC POT ' ,4523 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 100MM*90 PVC POTABLE ' ,5272 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 10CM*45 CONCRETO ' ,1372 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 10CM*90 DE CONCRETO ' ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 12MM*90 PVC POTABLE ROSC ' ,121 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 15CM*45 CONCRETO ' ,1098 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 15CM*90 CONCRETO ' ,1781 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 18MM*90 PVC POTABLE ' ,142 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 20CM*45 CONCRETO ' ,1072 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CODO 20CM*90 CONCRETO ' ,1268 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLOCACION MALLA CICLON ' ,9581 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLOCACIÓN PARED MEGABLOCK ' ,8286 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLOCACIÓN Y SUMINISTRO ACERO ' ,802 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA  PREFA 2 70 MT ' ,10695 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA  PREFA DUCHA  3 80 MT ' ,34613 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA  PREFA DUCHA 3 30 MT ' ,30640 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA PREFA 3 30 MT ' ,12166 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA PREFA 3 80 MT ' ,14559 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA PREFA PREV, ELEC, 3 80 MT ' ,16029 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA PREFA PREV,ELEC, 3 30 MT ' ,13621 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNA PREFA STANDAR  3 3 MTS ' ,11570 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCREMIX 50 KG ' ,2347 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO  PREMEZCLADO 175 KG/CM2 ' ,69920 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO EST, BLOQUE DISIPADOR, ($165/M3) ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO EST, UMBRAL DENTADO ($165/M3) ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO ESTRUCTURAL ($165/M3) ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO ESTRUCTURAL DIENTE ($165/M3) ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO MASIVO ($100/M3) ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 210 KG/CM2 ' ,72510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONDULETA 31 MM BOTAGUA ' ,1700 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONECTOR EMT 1 2 CM ' ,81 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONECTOR EMT 2 5 CM ' ,347 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONEXION PROVISIONAL  AGUA ' ,20717 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONEXIÓN PROVISIONAL ELÉCTRICA ' ,13984 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONEXION TANQUE PREFA ANGULAR ' ,10876 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONEXION TANQUE PREFA REDONDO ' ,4661 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONSTRUCCION CONDOMINIO ' ,207172 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUADRO 1A ' ,258 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUADRO SEMIDURO  50X 75X3 34 M ' ,2051 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUADRO SEMIDURO  50X1 00X3 34 M ' ,2755 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUBRE VALVULAS H,F, ' ,11135 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUMBRERA HG 26 /45 CM (18") ' ,2071 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUNETA 36CMX1,M MEDIA CAÑA ' ,3036 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CURVA CONDUIT 1 2 CM ' ,77 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CURVA CONDUIT 1 8 CM ' ,121 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DISCO P/CORTAR ' ,1703 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DURPANEL 4MM 0,61X0,61 ' ,196 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 10 CM ASTM C-443 ' ,435 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 15 CM ASTM C-443 ' ,709 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 20 CM ASTM C-443 ' ,890 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 30 CM ASTM C-443 ' ,999 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 40 CM ASTM C-443 ' ,1647 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE  HULE 80 CM ASTM C-443 ' ,3309 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE DE HULE 100MM ' ,859 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE DE HULE 150MM ' ,1486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE DE HULE 200MM ' ,1491 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE DE HULE 75MM ' ,486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE HULE 100 CM ASTM C-443 ' ,4500 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE HULE 120 CM ASTM C-443 ' ,5417 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE HULE 137 CM ASTM C-443 ' ,6764 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EMPAQUE HULE 152 CM ASTM C-443 ' ,7396 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ENTREPISO EN CONCRETO ' ,24860 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ENTREPISO EN RT CUBIERTA CONCRETO ' ,13984 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ENTREPISO PRETENSADO ' ,30039 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ENTREPISO SISTEMA  ZITRO ' ,7251 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ENZACATADO (JENJIBRILLO) ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EQ, BOMBEO RESIDENCIAL 3/4 HP ' ,238247 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESCALERA DE HIERRO ' ,466137 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESCALERA DE MADERA ' ,375499 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESCALERA EN CONCRETO ' ,691436 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESTANTERIA  MADERA ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FIBROLIT 100 1,22X2,44 8 MM ' ,9052 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FIBROLIT PLYCEM 61X61 CM/5 MM ' ,735 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FLANGER Y TAPA H,F, ' ,45059 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FORMALETA 2,5X30CM ' ,2034 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FORMALETA TABLA SUAVE 25X300 MM ' ,1207 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FRAGUA ' ,575 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FREGADERO 1X50 CMS FIBRA VIDRIO ' ,10759 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FREGADERO 50X100 ACRILICO CON CACHERA ' ,15537 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FREGADERO FIBRA 50X150 CON CACHERA ' ,25896 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FREGADERO HELEN FIBRA VIDRIO (1 ESCURR,) ' ,10358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FREGADERO ROXANA FIBRA VIDRIO (2 ESCURR,) ' ,12948 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FUENTE PARA AGUA ' ,28486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GABIONES (CANASTA) ' ,8286 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GANCHOS ' ,932 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GANCHOS ' ,932 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GIGANTON SEMIDURO SIN CEPILLO 100X100 MM ' ,2304 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GRUA DE 5 TON ' ,23306 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GUILLOTINA ' ,44024 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GUILLOTINA ' ,44024 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GYPSUM INTERIORES ( 4 X 6 "1/2) ' ,7547 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' HERRAMIENTAS BASICAS ' ,4143 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' HIERRO GALVANIZADO #28 ' ,921 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO BLANCO  #504 TIPO AZTECA ' ,174651 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO CENTAURO ASIENTO BLANCO ' ,174651 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO HABITAT BLANCO SIN ASIENTO ' ,25896 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO HYDRA ASIENTO BLANCO ' ,174651 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO TIPO CENTAURO ' ,174651 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INODORO TIPO ECONOMICO ' ,174651 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INSTALACIÓN EQUIPO BOMBEO PISCINA RESIDENC, ' ,699205 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INSTALACIÓN JACUZZI ' ,616336 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INTERCOMUNICADOR 20 AB, ' ,409164 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INTERRUPTOR  1 POLO  120 VOLTIOS ' ,2071 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LADRILLO 10X5X22CM BARRO ' ,198 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAJA ' ,3588 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA ESMALTADA BLANCA  NO 26 /1 07X1 83 ' ,9995 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA FIBROLIT 1 22X2 44 M /8 MM ' ,9052 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA FIBROLIT 1 22X2 44 M/ 11 MM ' ,14258 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA FIBROLIT 1 22X2 44 M/ 17 MM ' ,22405 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA FORMICA GRIS NEBOLA ' ,12094 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 28 ' ,4674 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 30 ' ,3983 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 32 ' ,2764 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X2 44 NO 28 ' ,5871 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X2 44 NO 30 ' ,5311 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X3 05 NO 28 ' ,7371 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X3 05 NO 30 ' ,8819 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 28 ' ,8588 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 30 ' ,7965 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 32 ' ,5674 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG LISO /0,91X1,83 /NO  24 ' ,6915 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG LISO/ 0,92X1,86 /NO  26 ' ,5700 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X1 83/ NO 30 ' ,3983 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X2 44 NO 26 ' ,7668 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X2 44/ NO 28 ' ,5871 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X2 44/ NO 30 ' ,5311 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 05/ NO 26 ' ,9594 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 05/ NO 28 ' ,7371 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 05/ NO 30 ' ,8819 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 66/ NO 26 ' ,11510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 66/ NO 28 ' ,8588 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG TECHO  81X3 66/ NO 30 ' ,7965 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG, TECHO / ,81X1,83 /NO 26 ' ,5752 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG, TECHO /,81X1,83 /NO 28 ' ,4674 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG, TECHO /,81X2,74/NO 26 ' ,7851 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA HG, TECHO /,81X3,66 /NO  28 ' ,8588 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA LISA 0 91X1 83 NO 26 ' ,5700 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 12 MM/2A ' ,13295 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 12MM/1A ' ,21108 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 15 MM/1A ' ,24157 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 18 MM ' ,27554 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 4 MM/1A ' ,8610 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 4 MM/2A ' ,4238 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 6 MM/2A ' ,7445 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 9 MM/1A ' ,18239 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 9 MM/2A ' ,11791 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA TECHO TRANSP, POLICARB,  81X1 83 ' ,6155 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA TECHO TRANSP, POLICARB,  81X3 66 ' ,15824 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LÁMINA TECHO TRANSP, PVC  81X1 83 ' ,1776 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LASTRE (ACARREO 10KM) ' ,8496 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAVAT FIBR VIDRIO BLANCO ' ,6018 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAVATORIO  BLANCO #400 ECONOMICO  S/PAR ' ,50589 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAVATORIO B EMBAJAD-BEIGE CON ACCESORIOS ' ,63041 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAVATORIO COLOR #402 PAR EMBAJ ' ,63041 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAVATORIO NEPTUNO BLANCO CON ACCESORIOS ' ,63041 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LIGA 220 P/ AGUA 3 M ' ,224 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LIJA #100 P/MADERA 3M ' ,218 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LIJA 100 P/ MADERA DE 3M ' ,218 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LIMPIEZA ($1000/HA) ' ,517930 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE CHORRO 12MM C/ROSC ' ,2707 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE CHORRO 12 MM CON ROSCA ' ,2707 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE CHORRO  12 MM ' ,2707 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE CONTROL CON ROSCA  12 MM ' ,2707 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE PASO 12 MM ' ,3173 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE PASO 12MM ' ,3173 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE PASO LISA  12 MM ' ,3173 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE PASO MIP LISA  12 MM ' ,3173 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVE DE PASO MIP LISA  18 MM ' ,3646 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LOSA DE CONCRETO DE 10 CM ' ,15537 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LOSETA 0,30X0,30 M ' ,6733 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MALLA ELECTROSOLDADA  15X15  NO 2 ' ,20996 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MALLA ELECTROSOLDADA 15X15 NO 1 ' ,17231 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MALLA GALV #12 5X5X1M=H ' ,2589 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO 1X3" C/4C ' ,569 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO 1X4" C/4C ' ,700 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO LAUREL 25X100 MM ' ,700 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO LAUREL 25X75 MM ' ,569 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO LAUREL 38X100 MM ' ,1050 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARCO LAUREL 38X75 MM ' ,787 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARMOL ' ,31075 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARTILLO NEUMATICO ' ,4661 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MEJORAMIENTO CAMINOS ($13000/KM) ' ,6733090 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MEMBRANA DE CURADO ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MEZCLA ASFALTICA ' ,16573 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MEZCLA ASFALTICA ' ,16573 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MINGITORIO ' ,160202 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO BAR ALBERGUE TURISTICO ' ,569723 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO COMEDOR EMPLEADOS ALBERGUE TURISTI ' ,2589650 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO HABITACIONES ALBERGUE TURISTICO ' ,1553790 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO LOBBY ALBERGUE TURISTICO ' ,414344 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO OFICINAS ALBERGUE TURISTICO ' ,569723 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO RESTAURANTE ALBERGUE TURISTICO ' ,6733090 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOBILIARIO SALONES ALBERGUE TURISTICO ' ,3496027 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MORTERO PEGAMIX 50 KG ' ,2347 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOSAICO  30X30 CM ' ,2071 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MOSTRADOR RECTANGULAR CON FORMICA ' ,77689 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLE BAÑO CON LAVATORIO ' ,64741 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLE COCINA ALTO Y BAJO ' ,33665 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLE PARA BAÑO VARGAS  SOBRE DE MÁRMOL ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLES ESPECIALES ' ,72510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUERTOS 4"X4" ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUROS RETENCIÓN TIPO MESA SYSTEM ($110/M2) ' ,56972 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' NIPLE H,G, D=100MM ' ,155 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' OCRE ROJO ' ,1489 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ORINAL ARTICO ' ,49203 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ORINAL WASHBROOK BLANCO ' ,163147 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PALA EXCAVADORA 325H ' ,33665 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PALADIANA ' ,10358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PARED CONVITEC ' ,7251 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PARED FIBROLIT MURO SECO ' ,7251 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PAREDES EN MEGABLOCK ' ,15537 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PARKET PINO 30X30 CM ' ,3884 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PARKET ROBLE 30X30 CM ' ,4402 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PARRILLA Y FLANGER H,F, ' ,28486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PEGAMENTO P/PVC ' ,4402 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PERFIL CAJON CG 1-14 101X100X1 90 MM ' ,21753 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PERFIL CAJON CG 1-16 100X100X1 50 MM ' ,15019 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PERFIL CAJON CG 1-17 100X100X1 35 MM ' ,21753 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PERFIL CAJON CG 1-18 100X100X1 20 MM ' ,15537 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 50 MM ' ,27 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 50MM ' ,27 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 63 MM ' ,45 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 63MM ' ,45 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 75 MM ' ,73 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PICAPORTE NEGRO DE 75MM ' ,73 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA (ACARREO 10KM) ' ,10967 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA BOLA ' ,7510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA BRUTA ' ,13857 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA QUINTILLA PRIMERA ' ,10682 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA QUINTILLA SEGUNDA ' ,10682 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEDRA VOLCAN ' ,5697 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEZA 5X10 CM ' ,517 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEZA ALMENDRO 2X4X4 PULG, ' ,6448 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEZA ALMENDRO 2X4X5 PULG, ' ,8027 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEZA ALMENDRO 2X4X6 PULG, ' ,9581 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PIEZAS 2"X8" ' ,3511 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PILA CONCRETO 1 BATEA 1X,53 MT ' ,37267 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PINTURA AGUA ' ,4159 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PINTURA ANTICORROSIVA ' ,13542 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PINTURA DE ACEITE ' ,5868 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PINTURA DE ACEITE ' ,5868 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PISO SURA 1ERA 25X75 MM ' ,725 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLAFON NO 21- M 10 0 CM ' ,393 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLASTIOLAV ' ,6075 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLASTIPLAY ' ,6670 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLATINA 1"X1/8" ' ,4668 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLYWOOD 4MM ,61X,61 B/BB ' ,828 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLYWOOD DE 4MM 1,22X2,44 ' ,4238 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' POLVO DE PIEDRA FINO ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' POLVO DE PORCELANA ' ,575 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PORTÓN COCHERA DE ARROLLAR 4,0X2,5 MT ' ,647412 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PORTÓN COCHERA HIERRO 4,0X2,5 MT ' ,383268 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PORTON HIERRO 5X2,5M ' ,274502 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PORTON LEVADIZO CONTROL 5X2,5M ' ,776895 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PORTÓN METÁLICO  ARROLLABLE 3X2,5M ' ,647412 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' POSTE CIRCULAR  8 0 MTS ' ,124303 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' POSTE SECCIÓN CIRCULAR 10 0 MTS ' ,176096 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' POSTE SECCIÓN CIRCULAR 9 0 MTS ' ,196813 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PRECINTA FIBROLIT 8MM ,3 ' ,864 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PRECINTA RICALIT 20 CM X 2 44 M X 8 MM ' ,1659 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PRECINTA RICALIT 30 CM X 2 44 M X 8 MM ' ,2379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PRECINTA RICALIT 40 CM X 2 44 M X 8 MM ' ,3172 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA ALUMINIO-VIDRIO ' ,481674 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA CAOBA C/TABLERO 0 90X2 10 M ' ,62151 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA CAOBILLA 0 90X2 10 M ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA CAOBILLA C/TABLERO PLYWOOD 0 90X2 1 M ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA EXTERIOR ' ,62151 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA EXTERIOR ESPECIAL ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA INTERIOR ESPECIAL ' ,18127 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA INTERIOR PLYWOOD ' ,14502 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA INTERNA DOBLE FORRO MADERA 0 85X2 1 M ' ,12430 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA PLYWOOD 0 90X2 10 M ' ,15537 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA PRINCIPAL CAOBILLA 4 TAB, 0 90X2 1 M ' ,64741 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA PRINCIPAL CAOBILLA OVALO 0 90X2 1 M ' ,95817 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PULIDORA ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUC 100X75MM LISA PVC ' ,3896 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUC 150X100MM LISA PVC ' ,11576 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 100X50 MM SDR-32,5 ' ,2158 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 100X75 MM SDR-32,5 ' ,7899 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 25X12 MM SDR-40 ' ,189 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 25X18 MM SDR-40 ' ,189 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 30X10 MM SDR-40 ' ,274 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 30X12 MM SDR-40 ' ,318 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 30X25 MM SDR-40 ' ,318 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 31X25 MM SDR-40 ' ,318 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 50X25 MM SDR-40 ' ,619 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 50X30 MM SDR-32,5 ' ,687 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REDUCCIÓN PVC 50X31 MM SDR-32,5 ' ,687 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA 1X2" C/C ' ,353 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA 1X2" S/C ' ,269 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA 1X3" S/C ' ,404 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA DE 1"X4" ' ,248 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA DE 2,5X20CM ' ,1227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA S/C 2,54X5CM L-C ' ,295 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA SEMIDURA 25X100 MM ' ,539 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA SEMIDURA 25X75 MM ' ,404 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REGLA SUAVE 25X50 MM ' ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REVESTIMIENTO (TRES MANOS) ' ,2719 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' REVESTIMIENTO PARA INTERIOR (10 LTS) ' ,4661 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ROBO E INCENDIO ' ,828 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RODAPIE 1/2X3" ' ,376 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RODAPIE CON MOLDURA ' ,569 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-113 (2 38MM) ' ,14800 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-116 (1,58MM) ' ,9349 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-313 (2 38MM) ' ,18358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-316 (1,58MM) ' ,11554 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-413 (2,38MM) ' ,22638 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RT-416 (1 58MM) ' ,13819 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SET BAÑO BEIGE 7 PZAS ' ,5681 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SILLETA 100X12MM LISA PVC ' ,3885 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SILLETA 100X18MM LISA PVC ' ,3107 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SILLETA 75X12MM LISA PVC ' ,4574 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SUBCONTRATO DE CORTE ' ,1243 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLA FORMALETA 1X12" ' ,1207 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA 1,2X7,5CM MACH ' ,150 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA 1/2*3" ' ,150 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA CORRIENTE 12X125 MM ' ,336 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA CRISTOBAL 12X75 MM ' ,725 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA LAUREL 12X125 MM ' ,321 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA LAUREL 12X75 MM ' ,269 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA NAZARENO 12X75 MM ' ,258 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLILLA SEMIDURA 1ERA 12X175 MM ' ,324 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLÓN ALMENDRO 12X2 PULG X 4 VARAS ' ,17091 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TABLONCILLO SURÁ 1X3 ' ,462 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAN, S, GRASAS PREFA 1,8X1  4X1 8 ' ,385857 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQ, AGUA PREFA 2 6X1  4X1 05 ' ,445419 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQ, SEPT, PREFA 1,8X1 4X1,0 ' ,284861 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE AGUA CALIENTE CAPACIDAD  150 LTS ' ,105800 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO FIB VIDRIO 150 LTS WM12 ' ,217530 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO FIB VIDRIO 450 LTS WM35 ' ,559364 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO FIB VIDRIO 55 LTS WM4 ' ,103586 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO METAL 135 LTS RJD36 ' ,201992 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO METAL 450 LTS RJD119 ' ,517930 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRO METAL 50 LTS RJH14 ' ,108765 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE HIDRONEUMÁTICO (50 GLS) ' ,258965 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE PARA AGUA (1000 LTS) ' ,72510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TANQUE PARA ALMACENAMIENTO ' ,72510 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 100MM HEMBRA PVC POTABLE ' ,2425 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 12MM HEMBRA PVC POTABLE ' ,71 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 150MM HEMBRA PVC POTABLE ' ,6644 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 18MM HEMBRA PVC POTABLE ' ,94 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 50MM HEMBRA PVC POTABLE ' ,419 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPON 75MM HEMBRA PVC POTABLE ' ,1379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPÓN LIMPIEZA PVC 100 MM ' ,994 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPÓN LIMPIEZA PVC 75 MM ' ,674 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE 100MM PVC ' ,7203 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE 100MM PVC SANIT ' ,5288 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE 100X100X75MM PVC ' ,9559 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE 150X100MM PVC ' ,24844 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE 75MM PVC ' ,4551 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE CONCRETO 10 CM ' ,2434 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEE CONCRETO D=15CM ' ,3729 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA ESMALTADA 2 00 M/NO 26 ' ,16573 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA ESMALTADA 2 10 M/NO 26 ' ,11409 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA ESMALTADA 3 50 M/NO 26 ' ,19016 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA MEDITERRANEO ' ,5101 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA SANTA FE CUMBRERA NATURAL ' ,880 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA SANTA FE TIPO S NATURAL ' ,880 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA TOLEDO ESMALTADA 1 09X0 70 NO 26 ' ,2796 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA TOLEDO ESMALTADA 1 09X2 1 NO 26 ' ,11409 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TEJA TOLEDO ESMALTADA 1 09X3 5 NO 26 ' ,19016 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TERRACÍN ' ,5179 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TERRAZO ' ,4562 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TORNILLOS P/TECHO ' ,20 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TRAMPA CON REGISTRO PVC 38 MM ' ,4258 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TRAMPA PVC 100 MM ' ,13179 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TRAMPA PVC 50 MM ' ,1660 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TRAMPA PVC 75 MM ' ,5735 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 17  100 MM ' ,46095 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 17  75 MM ' ,27968 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 26  50 MM ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 32,5  100 MM ' ,23306 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 32,5  75 MM ' ,14502 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 41  100 MM ' ,19163 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 41  75 MM ' ,11394 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA PARA DRENAJE  115 MM ' ,8286 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  100 MM  SANIT Y PLUVIAL ' ,20106 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  150 MM  SANIT Y PLUVIAL ' ,48453 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  200 MM  SANIT Y PLUVIAL ' ,138436 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  31 MM  SANIT Y PLUVIAL ' ,3456 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  38 MM  SANIT Y PLUVIAL ' ,3813 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  50 MM  SANIT Y PLUVIAL ' ,5553 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  62 MM  SANIT Y PLUVIAL ' ,10471 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 41  75 MM  SANIT Y PLUVIAL ' ,12323 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBERÍA SDR 50  100 MM  SANIT Y PLUVIAL ' ,16141 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO  CONCRETO PERFORADO 20 CM X 1 25 M ' ,6215 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO 0,1X1,25M PERF CONC ' ,2382 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO 25MMX6M H,G, LIVIAN ' ,14109 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO ABASTO 12MM EMPOTRA ' ,633 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO ABASTO PVC 1/2X1/2 LAVATORIO ' ,633 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO ABASTO PVC 7/8X1/2 INODORO ' ,633 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO ABASTO VINILO LAVATORIO 1/2X1/2 PULG ' ,633 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 10CMX1,25M ' ,1978 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 15CMX1,25M ' ,2589 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 20CMX1,25M ' ,4143 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 30CMX1,25M ' ,9219 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 40CMX1,25M ' ,14450 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 50CMX1,25M ' ,20717 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 60CMX1,25 ' ,25896 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 70CMX1,25M ' ,31593 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 80CMX1,25 ' ,36255 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-14 90 CMX1,25M ' ,48685 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 100 CM X 2 50 M C-IV ' ,356853 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 100 CM X 2 50 M C-V ' ,385857 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 100X2,50M C-III ' ,186454 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 107CMX2,50 C-III ' ,186454 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 120 CM X 2 50 M C-IV ' ,426256 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 120 CM X 2 50 M C-V ' ,459921 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 120CMX2,50CM C-III ' ,253267 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 152CMX2,00 C-III ' ,198885 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 183CMX1,25 C-III ' ,272949 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 213 CM X 1 25 M C-IV ' ,494623 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 213 CM X 1 25 M C-V ' ,647412 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 244 CM X 1 25 M C-IV ' ,763946 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 244 CM X 1 25 M C-V ' ,818329 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 40 CM X 1 25 M C-IV ' ,33665 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 40 CM X 1 25 M C-V ' ,47649 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 40 CM X 2 50 M C-IV ' ,67330 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 40 CM X 2 50 M C-IV ' ,67330 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 40 CM X 2 50 M C-V ' ,95299 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 50 CM X 1 25 M C-IV ' ,45059 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 50 CM X 1 25 M C-V ' ,56972 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 50 CM X 2 50 M C-IV ' ,90637 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 50 CM X 2 50 M C-V ' ,113944 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 60CMX1,25 C-III ' ,45577 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 70CMX1,25M C-III ' ,51793 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 80CMX1,25 C-III ' ,63705 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO C-76 90CMX1,25 C-III ' ,82868 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO 350 MM X 1 00 M ' ,3004 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO 375 MM X 1 00 M ' ,3988 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO 450 MM X 1 00 M ' ,4920 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO 525 MM X 1 00 M ' ,6681 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO PERFORADO 10 CM X 1 25 M ' ,880 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO PERFORADO 15 CM X 1 25 M ' ,1087 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONCRETO PERFORADO 25 CM X 1 25 M ' ,3004 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 12 MM X 3 M ' ,671 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 18 MM X 3M ' ,802 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 25 MM ' ,1219 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 31 MM ' ,1720 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 38 MM ' ,2462 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO CONDUIT 50 MM ' ,3863 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO EMT 31 MM X 3 M ' ,4237 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SCH-40 12MM PVC ' ,2812 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SCH-40 18MM PVC ' ,4302 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-17 18MM ' ,2364 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-17 19MM ' ,2364 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-26 100MM PVC ' ,32190 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-26 150MM PVC ' ,73815 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-26 25MM PVC ' ,2951 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-26 50MM PVC ' ,9102 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-26 75MM PVC ' ,19591 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-32,5 50MM ' ,7233 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-32,5 75MM ' ,15960 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-41,0 100MM ' ,20106 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TUBO SDR-50,0 100MM ' ,16141 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' UNION 50MM LISA PVC ' ,538 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' UNION REPARACION PVC 100M ' ,10358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' UNION REPARACION PVC 75M ' ,6215 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VALVULA 100MM COMPUERTA ' ,20717 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VALVULA 150MM COMPUERTA ' ,124303 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VALVULA 200MM COMPUERTA ' ,181275 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VALVULA 75MM COMPUERTA ' ,10358 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VÁLVULA DE AIRE BVK  12 MM ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA #2 (POR PESO) ' ,441 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA #3 (POR PESO) ' ,564 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA #4 (POR PESO) ' ,561 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA #5 (POR PESO) ' ,550 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA #6 (POR PESO) ' ,561 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA COOPERWELL 150 CM X 12 MM C/GAZA ' ,2109 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 2 LISA (6 MTS) ' ,653 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 3 (6 MTS) ' ,1878 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 3 LISA (6 MTS) ' ,2299 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 4 (6 MTS) ' ,3332 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 5 (6 MTS) ' ,5095 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 6 (6 MTS) ' ,7478 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 7 (6 MTS) ' ,10180 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 8 (6 MTS) ' ,13295 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VARILLA NO 9 (6 MTS) ' ,16433 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VENTANA METALICA ' ,3055 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VERJA HIERRO COLOCADA ' ,12948 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDIO ACRILICO 91 X 1,83 ' ,14880 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO ACRILICO 1,22 X 1,83 ' ,17485 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO ACRILICO 75 X 1,83 ' ,13114 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO POLARIZADO 1/8 ' ,15087 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO TRANSP, 1/8 ' ,6727 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO TRANSPARENTE 1/16 ' ,6417 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO TRANSPARENTE 1/8 ' ,4065 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIDRIO TRANSPARENTE ESCARCHADO ' ,5645 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOMA TELEFONICO ' ,1843 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SALIDA TELEVISOR COAXIAL ' ,3107 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' AGUARRAS ' ,870 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA DE BAÑO ' ,38844 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PILA CONCRETO DOS BATEAS ' ,11902 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVO DE ACERO 50 MM ' ,11 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CLAVO PARA TECHO CON ARANDELA ' ,1219 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LIMAHOYA HG 26 45 X 1 83 ' ,2522 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOPE PARA PUERTA ' ,326 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LLAVIN DOBLE PASO ' ,17077 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DRENAFLEX ' ,1035 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DUCHA PARA BAÑO ' ,54382 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN NO 2 AZUL ' ,3431 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN NO 2 NEGRO ' ,3431 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN NO 6 NEGRO ' ,1356 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' INTERRUPTOR ENTRADA 3 POLOS ' ,13125 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN NO 8 AZUL ' ,840 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CENTRO DE CARGA 8 CIRCUITOS ' ,15748 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BOMBILLO 75 WATTS ' ,204 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE THHN NO 12 AZUL ' ,322 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLAFON PORCELANA ' ,393 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPE ELECTRICO 20 METROS ' ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PASTILLA APAGADOR 3 VIAS ' ,1420 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GAZA EMT TIPO AMERICANO 12 MM ' ,14 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAJA CT 20-40 PARES ' ,41434 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CABLE TELEFONICO 2 PARES ' ,227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' LAMPARA FLUORESCENTE ' ,25896 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PARA PAVIMENTO ' ,75099 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 70 KG/CM2 ' ,62151 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 105 KG/CM2 ' ,66295 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 140 KG/CM2 ' ,69920 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 225 KG/CM2 ' ,79243 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 245 KG/CM2 ' ,81832 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 280 KG/CM2 ' ,88048 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 315 KG/CM2 ' ,89601 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 350 KG/CM2 ' ,93227 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CONCRETO PREMEZCLADO 400 KG/CM2 ' ,98406 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MARMOLINA ' ,67 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MORTERO MAXIGLAS PARA VIDRIO ' ,5179 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' OCRE AMARILLO ' ,1667 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PILOTE DE CONCRETO DIAMETRO 60 CM ' ,13466 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' RETIRO DE ESCOMBROS ' ,2589 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SERVICIO BOMBEO TELESCOPICA ALCANCE 28 MTS ' ,8157 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SERVICIO BOMBEO TELESCOPICA ALCANCE 32 MTS ' ,10436 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOBA CEMENTO 10 KG/CM2 ' ,27859 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOBA CEMENTO 15 KG/CM2 ' ,30014 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOBA CEMENTO 25 KG/CM2 ' ,32080 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOBA CEMENTO 35 KG/CM2 ' ,34597 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TOBA CEMENTO 75 KG/CM2 ' ,45551 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' YESO ' ,471 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EXTINTOR 10 LIBRAS CLASE ABC ' ,9291 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EXTINTOR 20 LIBRAS CLASE ABC ' ,13336 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' EXTINTOR 30 LIBRAS CLASE ABC ' ,16029 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' AGARRADERA TINA CROMADA ' ,19303 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DESAGUE TINA AUTOMATICO ' ,30100 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DUCHA LORENZETTI LORENDUXA ' ,12347 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DUCHA LORENZETTI PARA LAVATORIO ' ,19520 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DUCHA  MASAJE ' ,11270 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' DUCHA TELEFONO PARA MASAJE ' ,20147 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FLUXOMETRO ELECTRONICO ' ,145020 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FLUXOMETRO PARA INODORO ' ,77689 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' FLUXOMETRO PARA ORINAL ' ,90637 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLE AEREO PARA COCINA ' ,163147 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MUEBLE PARA FREGADERO ' ,77689 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARENA RODADA DIAM MAX 10 MM ' ,6215 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARENA GRUESA BAJO 3/8 PULG ' ,5179 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' GRAVA DE 3/8 A 3/4 PULG ' ,3677 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARENA MORTERO ' ,7768 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ARENA POLVO DE ROCA ' ,4920 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CAL HIDRAULICA ' ,1812 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESTUCO INTERIOR ' ,3004 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ESTUCO EXTERIOR ' ,3262 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MELAMINA 10 MM (1 83X2 5 M) ' ,4531 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' MELAMINA 16 MM (1 83X2 50 M) ' ,5101 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BARNIZ MARINO ' ,1165 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' BARNIZ HIDROREPELENTE ' ,1113 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLANCHA TERMOAISLANTE REVESTIDA 1000X2000X30 M ' ,1859 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PLANCHA TERMOAISLANTE POLIESTIRENO 1220X610X20 ' ,1973 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CUBREPISO TODO USO ' ,2341 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALFOMBRA PARA HOGAR U OFICINA ' ,7701 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ALFOMBRA RESIDENCIAL 14 MM ESPESOR ' ,13683 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' ADHESIVO PARA ALFOMBRAS ' ,42786 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VINOLEUM ALTO TRAFICO ' ,14180 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' PUERTA ALUMINIO 2 HOJAS 1 8X2 5 MT ' ,147610 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CRISTAL INCOLORO 2 00 MM ESPESOR ' ,3366 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CRISTAL INCOLORO 3 00 MM ESPESOR ' ,3656 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CRISTAL INCOLORO 10 0 MM ESPESOR ' ,12181 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' SAUNA EN CIPRES ' ,178685 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPIA BLOQUE SISADO (H=2 50 M) ' ,35737 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' TAPIA BALDOSAS-COLUMNAS PREFA (H=2 0 M) ' ,28486 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CERCA ALAMBRE 6 HILOS POSTE CONCRETO ' ,3211 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNAS DE CONCRETO ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIGAS DE CONCRETO ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' COLUMNAS DE CONCRETO ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIGAS DE CONCRETO ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' VIGAS CONCRETO ' ,155379 )
 INSERT INTO [dbo].[Material]([Nombre],[PrecioUnitario]) Values(' CORNIZA ' ,2071 )

 GO

 Select * From Material