USE [TEConstruye]
GO




 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ACCESORIOS PARA BAÑO ',' Unidad ',5681 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ACCESORIOS PARA BAÑO ESPECIAL ',' Unidad ',5681 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ACEITE ',' Lts ',833 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ACIDO MURIÁTICO ',' Galón ',1569 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADAPTADOR  100MM HEMBRA PVC POTABLE ',' Un ',2894 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADITIVO  ACELERANTE DE FRAGUA NORMAL ',' S500cc ',2211 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADITIVO  REDUCTOR DE AGUA ',' Litro ',1087 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADITIVO IMPERMEABILIZANTE ',' Litro ',1937 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADITIVO REDUCTOR AGUA-RETARDAD,, ',' Litro ',1274 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADOQUIN 10X20X8 CMS ',' Unidad ',3428 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADOQUIN 24X22X8 CMS ',' Unidad ',3428 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALAMBRE DE AMARRE #16 ',' Kg ',639 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALAMBRE GALVANIZADO NO 16 ',' Kg ',849 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALFAJILLA SEMIDURA SIN CEPILLO 50X100 MM ',' Unidad ',1059 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALFARJIA 2"X6" ',' unidad ',1491 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALFOMBRAS ',' m2 ',14838 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ANG 6X50X50X6M CALIENTE ',' Un ',18615 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' APAGADOR NO 52 SUP, ',' Un ',870 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' APAGADOR NO 54 DOBLE SUP ',' Un ',735 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' APLANADORA 210-A BUF-BOMA ',' HR ',22115 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' APTOS HASTA 12 EQUIPO BOMBEO ',' Unid ',269323 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARENA DE RÍO ',' m3 ',15990 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARTESONADO 50X1,25X3,34 ',' unidad ',11394 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARTESONADO SEMIDURO 50X1 50X3 34 M ',' Unidad ',8136 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BAJANTE HG 26 /30 CM (12") ',' Unidad ',2071 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BAJANTE HG CANOA 2X4 PULG ',' Unidad ',2071 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BAJANTE HG NO 28/ 1 83 M ',' Unidad ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA  CARGADOR 1 5 MT ',' Unidad ',3868 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA  CARGADOR 1 75 MT ',' Unidad ',4837 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA BANQUINA 1 50 MT ',' Unidad ',5852 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA BANQUINA 1 75 MT ',' Unidad ',6272 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA  1 95X50 MT ',' Unidad ',6080 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 0 45XO 5 MT ',' Unidad ',1538 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 0 75X0 5 MT ',' Unidad ',2486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 0X0 5 MT ',' Unidad ',3413 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 25X0 5 MT ',' Unidad ',4164 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 37X0 5 MT ',' Unidad ',4754 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 45X0 5 MT ',' Unidad ',4961 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 5X0 5 MT ',' Unidad ',4775 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 1 75X0 5 MT ',' Unidad ',6039 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BALDOSA PREFA 4CM X 50CM ',' m2 ',6417 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BARANDAS Y PASAMANOS ',' ml ',1600 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BASA DE CONCRETO 40 CM ',' Unidad ',934 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BASE PARA MEDIDOR USA ',' Unidad ',35866 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BATIDORA ',' HR ',3278 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BATIDORA 3 5 M3/HR ',' HR ',25186 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BATIENTE LAUREL LISA 12X25MM ',' 0,84mt ',113 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BIDET PLAZA LOZA BLANCA ',' Unidad ',94009 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BIDET RENAISSANCE LOZA BLANCA ',' Unidad ',75125 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BISAGRA ,75X,75 HIERRO ',' Par ',409 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BLOQUE 10*20*40 ',' Unidad ',273 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BLOQUE 12*20*40 ',' Unidad ',294 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BLOQUE 15X20X40 ',' Unidad ',386 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BLOQUE CONCRETO 20X20X40 CMS ',' Unidad ',486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BLOQUE TIPO A ',' m2 ',3470 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA AGUAS NEGRAS 0,5 HP RJSE55 ',' Unidad ',308168 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA AGUAS NEGRAS 0,75 HP RJSE75 ',' Unidad ',427292 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CENTRÍFUGA  3HP HI 300SPHE MONO ',' Unidad ',409164 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CENTRÍFUGA 2 HP HI 200RSP MONO ',' Unidad ',212351 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CENTRÍFUGA 3 HP 300SPHE TRI ',' Unidad ',367730 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CENTRÍFUGA 5 HP 500 SPHE MONO ',' Unidad ',538647 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CENTRÍFUGA PARA AGUA ',' Unidad ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA CON TANQUE HIDRONEUMATICO ',' Unidad ',818329 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA RED JACKET 0,5 HP HF 502SWC ',' Unidad ',124303 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA RED JACKET 0,5 HP HF 50RJ ',' Unidad ',129482 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA RED JACKET 1 HP HF 1002SWC ',' Unidad ',147610 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA RED JACKET 1,5 HP HI 1502SWC ',' Unidad ',170916 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA RED JACKET 1HP HF 100RJ ',' Unidad ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 0,5 HP 10 GPM ',' Unidad ',222709 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 1 HP 22 GPM ',' Unidad ',282271 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 2 HP 28 GPM ',' Unidad ',429881 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 3 HP 18 GPM ',' Unidad ',631874 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 5 HP 50 GPM ',' Unidad ',880481 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBA SUMERGIBLE 5 HP 55 GPM ',' Unidad ',906377 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBEO CONCRETO ',' m3 ',4143 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOTAG LIMAT LIMAH CUMB, ',' ml ',3262 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BREACKER 1 X 015 AMP ',' Un ',2931 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BREACKER 1 X 020 AMP ',' Un ',2931 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BREACKER 1 X 040 AMP ',' Un ',3623 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BREACKER 2 X 040 AMP ',' Un ',8408 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BROCHAS ',' Un ',2127 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BROCHAS ',' Un ',2127 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABEZOTE DE HIDRANTE ',' Un ',139841 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN/THW NGM , 14 ',' ML ',239 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN/THW NGM, 10 ',' ML ',538 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN/THW NGM, 12 ',' ML ',322 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE TW/ THW NO 6 ',' ML ',517 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE TW/THW NO 8 ',' ML ',310 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CACHERA ',' Un ',40373 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CACHERA ',' Un ',40373 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CACHERA FREGADERO ',' Unidad ',30228 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CACHERA PARA BAÑO ',' Unidad ',45448 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CACHERA PARA FREGADERO METAL SENCILLA ',' Unidad ',30228 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CADENILLO 2"X4" ',' m ',1059 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CADENILLO 2"X6" ',' m ',1491 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAJA COND, RECTANGULAR ',' Un ',173 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAJAS MEDIDORES AGUA POTABLE ',' Unidad ',4661 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAL FINA ',' Kg ',39 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CALENTADOR AGUA (40 GLS) ',' Unidad ',105800 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAMION ',' VIAJE ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAMIÓN  20 TONELADAS ',' HR ',8804 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANALETA ESTRUCTURAL 0 74X4 57 NO 26 ',' Lámina ',6266 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANALETA ESTRUCTURAL 0 74X6 10 NO 26 ',' Lámina ',8338 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANALETA ESTRUCTURAL 0 74X7 01 NO 26 ',' Lámina ',9581 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANALETA ESTRUCTURAL 0 74X7 62 NO 26 ',' Lámina ',10410 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANOA HG 26/ 30 CM  (12") ',' Unidad ',4402 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CANOAS Y BAJANTES INSTALADOS ',' ml ',5697 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CARRETILLO FERRO LLANTA DE HULE ',' Unidad ',19000 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CARRETILLOS ',' H-J ',103 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CELOSIAS COLOCADAS ',' m2 ',34183 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CEMENTO ',' Saco ',4331 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CENICERO 10CM ALCARRAZA ',' Un ',3368 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CENTRAL HASTA 24 ABONADOS, 8 TRONCALES ',' Unid ',5627309 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CENTRO DE CARGA 6F EMBUTIR ',' Un ',16791 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERAMICA 33X33 CMS ',' M2 ',2339 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERRADURA  ESPECIAL ',' Unidad ',16314 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERRADURA BOTON ESPECIAL ',' Unidad ',9581 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERRADURA CORRIENTE ',' Un ',10358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERRADURA CORRIENTE ',' Un ',21235 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERRADURA ESPECIAL ',' Un ',36255 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CIELOS DE GYPSUM ',' m2 ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVO DE 38MM ACERO ',' Unidad ',11 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVO PARA TECHO 63MM ',' Kg ',1219 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVOS 100 MM (4") ',' Kg ',779 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVOS DE 1 1/2" ',' Kgs ',870 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVOS DE 1" C/CABEZA ',' Kg ',1010 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVOS DE 65 MM (2 1/2") ',' Kgs ',620 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLOSET ',' ml ',119123 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 100MM*45 PVC POT ',' Un ',4523 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 100MM*90 PVC POTABLE ',' Un ',5272 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 10CM*45 CONCRETO ',' Un ',1372 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 10CM*90 DE CONCRETO ',' Un ',0 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 12MM*90 PVC POTABLE ROSC ',' Un ',121 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 15CM*45 CONCRETO ',' Un ',1098 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 15CM*90 CONCRETO ',' Un ',1781 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 18MM*90 PVC POTABLE ',' Unidad ',142 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 20CM*45 CONCRETO ',' Un ',1072 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CODO 20CM*90 CONCRETO ',' Un ',1268 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLOCACION MALLA CICLON ',' m2 ',9581 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLOCACIÓN PARED MEGABLOCK ',' m2 ',8286 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLOCACIÓN Y SUMINISTRO ACERO ',' kg ',802 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA  PREFA 2 70 MT ',' Unidad ',10695 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA  PREFA DUCHA  3 80 MT ',' Unidad ',34613 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA  PREFA DUCHA 3 30 MT ',' Unidad ',30640 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA PREFA 3 30 MT ',' Unidad ',12166 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA PREFA 3 80 MT ',' Unidad ',14559 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA PREFA PREV, ELEC, 3 80 MT ',' Unidad ',16029 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA PREFA PREV,ELEC, 3 30 MT ',' Unidad ',13621 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNA PREFA STANDAR  3 3 MTS ',' Unidad ',11570 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCREMIX 50 KG ',' Saco ',2347 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO  PREMEZCLADO 175 KG/CM2 ',' M3 ',69920 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO EST, BLOQUE DISIPADOR, ($165/M3) ',' M3 ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO EST, UMBRAL DENTADO ($165/M3) ',' M3 ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO ESTRUCTURAL ($165/M3) ',' M3 ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO ESTRUCTURAL DIENTE ($165/M3) ',' M3 ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO MASIVO ($100/M3) ',' M3 ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 210 KG/CM2 ',' M3 ',72510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONDULETA 31 MM BOTAGUA ',' Un ',1700 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONECTOR EMT 1 2 CM ',' Un ',81 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONECTOR EMT 2 5 CM ',' Un ',347 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONEXION PROVISIONAL  AGUA ',' Gbl ',20717 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONEXIÓN PROVISIONAL ELÉCTRICA ',' Global ',13984 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONEXION TANQUE PREFA ANGULAR ',' Unidad ',10876 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONEXION TANQUE PREFA REDONDO ',' Unidad ',4661 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONSTRUCCION CONDOMINIO ',' M2 ',207172 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUADRO 1A ',' Dm3 ',258 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUADRO SEMIDURO  50X 75X3 34 M ',' Unidad ',2051 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUADRO SEMIDURO  50X1 00X3 34 M ',' Unidad ',2755 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUBRE VALVULAS H,F, ',' Un ',11135 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUMBRERA HG 26 /45 CM (18") ',' Unidad ',2071 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUNETA 36CMX1,M MEDIA CAÑA ',' Un ',3036 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CURVA CONDUIT 1 2 CM ',' Un ',77 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CURVA CONDUIT 1 8 CM ',' Un ',121 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DISCO P/CORTAR ',' Un ',1703 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DURPANEL 4MM 0,61X0,61 ',' Un ',196 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 10 CM ASTM C-443 ',' Unidad ',435 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 15 CM ASTM C-443 ',' Unidad ',709 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 20 CM ASTM C-443 ',' Unidad ',890 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 30 CM ASTM C-443 ',' Unidad ',999 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 40 CM ASTM C-443 ',' Unidad ',1647 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE  HULE 80 CM ASTM C-443 ',' Unidad ',3309 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE DE HULE 100MM ',' Un ',859 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE DE HULE 150MM ',' Un ',1486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE DE HULE 200MM ',' Un ',1491 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE DE HULE 75MM ',' Un ',486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE HULE 100 CM ASTM C-443 ',' Unidad ',4500 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE HULE 120 CM ASTM C-443 ',' Unidad ',5417 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE HULE 137 CM ASTM C-443 ',' Unidad ',6764 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EMPAQUE HULE 152 CM ASTM C-443 ',' Unidad ',7396 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ENTREPISO EN CONCRETO ',' m2 ',24860 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ENTREPISO EN RT CUBIERTA CONCRETO ',' m2 ',13984 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ENTREPISO PRETENSADO ',' m2 ',30039 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ENTREPISO SISTEMA  ZITRO ',' m2 ',7251 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ENZACATADO (JENJIBRILLO) ',' m2 ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EQ, BOMBEO RESIDENCIAL 3/4 HP ',' Unid ',238247 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESCALERA DE HIERRO ',' Unidad ',466137 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESCALERA DE MADERA ',' Unidad ',375499 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESCALERA EN CONCRETO ',' Unidad ',691436 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESTANTERIA  MADERA ',' m2 ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FIBROLIT 100 1,22X2,44 8 MM ',' Lamina ',9052 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FIBROLIT PLYCEM 61X61 CM/5 MM ',' Unidad ',735 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FLANGER Y TAPA H,F, ',' Un ',45059 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FORMALETA 2,5X30CM ',' m ',2034 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FORMALETA TABLA SUAVE 25X300 MM ',' Unidad ',1207 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FRAGUA ',' Kg ',575 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FREGADERO 1X50 CMS FIBRA VIDRIO ',' Unidad ',10759 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FREGADERO 50X100 ACRILICO CON CACHERA ',' Unidad ',15537 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FREGADERO FIBRA 50X150 CON CACHERA ',' Unidad ',25896 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FREGADERO HELEN FIBRA VIDRIO (1 ESCURR,) ',' Unidad ',10358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FREGADERO ROXANA FIBRA VIDRIO (2 ESCURR,) ',' Unidad ',12948 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FUENTE PARA AGUA ',' Unidad ',28486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GABIONES (CANASTA) ',' M3 ',8286 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GANCHOS ',' Un ',932 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GANCHOS ',' Unidad ',932 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GIGANTON SEMIDURO SIN CEPILLO 100X100 MM ',' Unidad ',2304 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GRUA DE 5 TON ',' HR ',23306 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GUILLOTINA ',' m2 ',44024 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GUILLOTINA ',' Un ',44024 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GYPSUM INTERIORES ( 4 X 6 "1/2) ',' Un ',7547 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' HERRAMIENTAS BASICAS ',' UNID ',4143 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' HIERRO GALVANIZADO #28 ',' m2 ',921 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO BLANCO  #504 TIPO AZTECA ',' Unidad ',174651 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO CENTAURO ASIENTO BLANCO ',' Unidad ',174651 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO HABITAT BLANCO SIN ASIENTO ',' Unidad ',25896 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO HYDRA ASIENTO BLANCO ',' Unidad ',174651 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO TIPO CENTAURO ',' Unidad ',174651 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INODORO TIPO ECONOMICO ',' Unidad ',174651 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INSTALACIÓN EQUIPO BOMBEO PISCINA RESIDENC, ',' Unidad ',699205 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INSTALACIÓN JACUZZI ',' Unidad ',616336 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INTERCOMUNICADOR 20 AB, ',' Unidad ',409164 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INTERRUPTOR  1 POLO  120 VOLTIOS ',' Un ',2071 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LADRILLO 10X5X22CM BARRO ',' Unidad ',198 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAJA ',' m2 ',3588 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA ESMALTADA BLANCA  NO 26 /1 07X1 83 ',' Unidad ',9995 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA FIBROLIT 1 22X2 44 M /8 MM ',' Unidad ',9052 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA FIBROLIT 1 22X2 44 M/ 11 MM ',' Unidad ',14258 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA FIBROLIT 1 22X2 44 M/ 17 MM ',' Unidad ',22405 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA FORMICA GRIS NEBOLA ',' Unidad ',12094 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 28 ',' Lámina ',4674 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 30 ',' Lámina ',3983 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X1 83 NO 32 ',' Lámina ',2764 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X2 44 NO 28 ',' Lámina ',5871 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X2 44 NO 30 ',' Lámina ',5311 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X3 05 NO 28 ',' Lámina ',7371 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X3 05 NO 30 ',' Lámina ',8819 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 28 ',' Lámina ',8588 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 30 ',' Lámina ',7965 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA GALVANIZADA 0 81X3 66 NO 32 ',' Lámina ',5674 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG LISO /0,91X1,83 /NO  24 ',' Unidad ',6915 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG LISO/ 0,92X1,86 /NO  26 ',' Unidad ',5700 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X1 83/ NO 30 ',' Unidad ',3983 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X2 44 NO 26 ',' Unidad ',7668 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X2 44/ NO 28 ',' Unidad ',5871 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X2 44/ NO 30 ',' Unidad ',5311 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 05/ NO 26 ',' Unidad ',9594 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 05/ NO 28 ',' Unidad ',7371 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 05/ NO 30 ',' Unidad ',8819 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 66/ NO 26 ',' Unidad ',11510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 66/ NO 28 ',' Unidad ',8588 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG TECHO  81X3 66/ NO 30 ',' Unidad ',7965 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG, TECHO / ,81X1,83 /NO 26 ',' Unidad ',5752 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG, TECHO /,81X1,83 /NO 28 ',' Unidad ',4674 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG, TECHO /,81X2,74/NO 26 ',' Unidad ',7851 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA HG, TECHO /,81X3,66 /NO  28 ',' Unidad ',8588 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA LISA 0 91X1 83 NO 26 ',' Lámina ',5700 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 12 MM/2A ',' Unidad ',13295 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 12MM/1A ',' Unidad ',21108 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 15 MM/1A ',' Unidad ',24157 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 18 MM ',' Unidad ',27554 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 4 MM/1A ',' Unidad ',8610 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 4 MM/2A ',' Unidad ',4238 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 6 MM/2A ',' Unidad ',7445 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 9 MM/1A ',' Unidad ',18239 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA PLYWOOD 1 22 M X 2 44 M X 9 MM/2A ',' Unidad ',11791 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA TECHO TRANSP, POLICARB,  81X1 83 ',' Unidad ',6155 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA TECHO TRANSP, POLICARB,  81X3 66 ',' Unidad ',15824 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LÁMINA TECHO TRANSP, PVC  81X1 83 ',' Unidad ',1776 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LASTRE (ACARREO 10KM) ',' m3 ',8496 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAVAT FIBR VIDRIO BLANCO ',' Unidad ',6018 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAVATORIO  BLANCO #400 ECONOMICO  S/PAR ',' Unidad ',50589 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAVATORIO B EMBAJAD-BEIGE CON ACCESORIOS ',' Unidad ',63041 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAVATORIO COLOR #402 PAR EMBAJ ',' Unidad ',63041 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAVATORIO NEPTUNO BLANCO CON ACCESORIOS ',' Unidad ',63041 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LIGA 220 P/ AGUA 3 M ',' Pliego ',224 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LIJA #100 P/MADERA 3M ',' Plg ',218 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LIJA 100 P/ MADERA DE 3M ',' Pliego ',218 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LIMPIEZA ($1000/HA) ',' Ha ',517930 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE CHORRO 12MM C/ROSC ',' Un ',2707 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE CHORRO 12 MM CON ROSCA ',' Unidad ',2707 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE CHORRO  12 MM ',' Unidad ',2707 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE CONTROL CON ROSCA  12 MM ',' Unidad ',2707 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE PASO 12 MM ',' Unidad ',3173 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE PASO 12MM ',' Un ',3173 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE PASO LISA  12 MM ',' Unidad ',3173 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE PASO MIP LISA  12 MM ',' Unidad ',3173 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVE DE PASO MIP LISA  18 MM ',' Unidad ',3646 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LOSA DE CONCRETO DE 10 CM ',' m2 ',15537 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LOSETA 0,30X0,30 M ',' m2 ',6733 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MALLA ELECTROSOLDADA  15X15  NO 2 ',' M2 ',20996 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MALLA ELECTROSOLDADA 15X15 NO 1 ',' M2 ',17231 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MALLA GALV #12 5X5X1M=H ',' m ',2589 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO 1X3" C/4C ',' m ',569 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO 1X4" C/4C ',' m ',700 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO LAUREL 25X100 MM ',' Unidad ',700 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO LAUREL 25X75 MM ',' Unidad ',569 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO LAUREL 38X100 MM ',' Unidad ',1050 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARCO LAUREL 38X75 MM ',' Unidad ',787 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARMOL ',' m2 ',31075 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARTILLO NEUMATICO ',' Hr ',4661 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MEJORAMIENTO CAMINOS ($13000/KM) ',' Km ',6733090 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MEMBRANA DE CURADO ',' Litro ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MEZCLA ASFALTICA ',' Ton ',16573 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MEZCLA ASFALTICA ',' Ton ',16573 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MINGITORIO ',' Unidad ',160202 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO BAR ALBERGUE TURISTICO ',' Unidad ',569723 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO COMEDOR EMPLEADOS ALBERGUE TURISTI ',' Unidad ',2589650 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO HABITACIONES ALBERGUE TURISTICO ',' Unidad ',1553790 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO LOBBY ALBERGUE TURISTICO ',' Unidad ',414344 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO OFICINAS ALBERGUE TURISTICO ',' Unidad ',569723 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO RESTAURANTE ALBERGUE TURISTICO ',' Unidad ',6733090 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOBILIARIO SALONES ALBERGUE TURISTICO ',' Unidad ',3496027 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MORTERO PEGAMIX 50 KG ',' Saco ',2347 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOSAICO  30X30 CM ',' m2 ',2071 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MOSTRADOR RECTANGULAR CON FORMICA ',' ml ',77689 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLE BAÑO CON LAVATORIO ',' ml ',64741 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLE COCINA ALTO Y BAJO ',' Unidad ',33665 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLE PARA BAÑO VARGAS  SOBRE DE MÁRMOL ',' Unidad ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLES ESPECIALES ',' ml ',72510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUERTOS 4"X4" ',' m ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUROS RETENCIÓN TIPO MESA SYSTEM ($110/M2) ',' m2 ',56972 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' NIPLE H,G, D=100MM ',' Un ',155 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' OCRE ROJO ',' Kg ',1489 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ORINAL ARTICO ',' Unidad ',49203 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ORINAL WASHBROOK BLANCO ',' Unidad ',163147 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PALA EXCAVADORA 325H ',' HR ',33665 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PALADIANA ',' m2 ',10358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PARED CONVITEC ',' m2 ',7251 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PARED FIBROLIT MURO SECO ',' m2 ',7251 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PAREDES EN MEGABLOCK ',' m2 ',15537 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PARKET PINO 30X30 CM ',' M2 ',3884 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PARKET ROBLE 30X30 CM ',' M2 ',4402 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PARRILLA Y FLANGER H,F, ',' Un ',28486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PEGAMENTO P/PVC ',' Lts ',4402 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PERFIL CAJON CG 1-14 101X100X1 90 MM ',' Unidad ',21753 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PERFIL CAJON CG 1-16 100X100X1 50 MM ',' Unidad ',15019 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PERFIL CAJON CG 1-17 100X100X1 35 MM ',' Unidad ',21753 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PERFIL CAJON CG 1-18 100X100X1 20 MM ',' Unidad ',15537 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 50 MM ',' Unidad ',27 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 50MM ',' Unidad ',27 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 63 MM ',' Unidad ',45 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 63MM ',' Unidad ',45 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 75 MM ',' Unidad ',73 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PICAPORTE NEGRO DE 75MM ',' Unidad ',73 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA (ACARREO 10KM) ',' m3 ',10967 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA BOLA ',' m2 ',7510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA BRUTA ',' m3 ',13857 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA QUINTILLA PRIMERA ',' M3 ',10682 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA QUINTILLA SEGUNDA ',' M3 ',10682 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEDRA VOLCAN ',' m2 ',5697 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEZA 5X10 CM ',' Dm3 ',517 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEZA ALMENDRO 2X4X4 PULG, ',' Unidad ',6448 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEZA ALMENDRO 2X4X5 PULG, ',' Unidad ',8027 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEZA ALMENDRO 2X4X6 PULG, ',' Unidad ',9581 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PIEZAS 2"X8" ',' m ',3511 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PILA CONCRETO 1 BATEA 1X,53 MT ',' Unidad ',37267 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PINTURA AGUA ',' Litro ',4159 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PINTURA ANTICORROSIVA ',' Litro ',13542 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PINTURA DE ACEITE ',' Litro ',5868 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PINTURA DE ACEITE ',' Litro ',5868 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PISO SURA 1ERA 25X75 MM ',' Unidad ',725 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLAFON NO 21- M 10 0 CM ',' Unidad ',393 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLASTIOLAV ',' Unidad ',6075 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLASTIPLAY ',' Unidad ',6670 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLATINA 1"X1/8" ',' Unidad ',4668 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLYWOOD 4MM ,61X,61 B/BB ',' Lam ',828 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLYWOOD DE 4MM 1,22X2,44 ',' Un ',4238 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' POLVO DE PIEDRA FINO ',' M3 ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' POLVO DE PORCELANA ',' Kg ',575 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PORTÓN COCHERA DE ARROLLAR 4,0X2,5 MT ',' Unidad ',647412 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PORTÓN COCHERA HIERRO 4,0X2,5 MT ',' Unidad ',383268 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PORTON HIERRO 5X2,5M ',' Unidad ',274502 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PORTON LEVADIZO CONTROL 5X2,5M ',' Unidad ',776895 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PORTÓN METÁLICO  ARROLLABLE 3X2,5M ',' Unidad ',647412 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' POSTE CIRCULAR  8 0 MTS ',' Unidad ',124303 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' POSTE SECCIÓN CIRCULAR 10 0 MTS ',' Unidad ',176096 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' POSTE SECCIÓN CIRCULAR 9 0 MTS ',' Unidad ',196813 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PRECINTA FIBROLIT 8MM ,3 ',' m ',864 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PRECINTA RICALIT 20 CM X 2 44 M X 8 MM ',' Unidad ',1659 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PRECINTA RICALIT 30 CM X 2 44 M X 8 MM ',' Unidad ',2379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PRECINTA RICALIT 40 CM X 2 44 M X 8 MM ',' Unidad ',3172 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA ALUMINIO-VIDRIO ',' Unidad ',481674 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA CAOBA C/TABLERO 0 90X2 10 M ',' Unidad ',62151 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA CAOBILLA 0 90X2 10 M ',' Unidad ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA CAOBILLA C/TABLERO PLYWOOD 0 90X2 1 M ',' Unidad ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA EXTERIOR ',' Unidad ',62151 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA EXTERIOR ESPECIAL ',' Unidad ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA INTERIOR ESPECIAL ',' Unidad ',18127 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA INTERIOR PLYWOOD ',' Unidad ',14502 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA INTERNA DOBLE FORRO MADERA 0 85X2 1 M ',' Unidad ',12430 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA PLYWOOD 0 90X2 10 M ',' Unidad ',15537 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA PRINCIPAL CAOBILLA 4 TAB, 0 90X2 1 M ',' Unidad ',64741 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA PRINCIPAL CAOBILLA OVALO 0 90X2 1 M ',' Unidad ',95817 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PULIDORA ',' M2 ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUC 100X75MM LISA PVC ',' Unidad ',3896 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUC 150X100MM LISA PVC ',' Unidad ',11576 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 100X50 MM SDR-32,5 ',' Unidad ',2158 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 100X75 MM SDR-32,5 ',' Unidad ',7899 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 25X12 MM SDR-40 ',' Unidad ',189 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 25X18 MM SDR-40 ',' Unidad ',189 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 30X10 MM SDR-40 ',' Unidad ',274 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 30X12 MM SDR-40 ',' Unidad ',318 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 30X25 MM SDR-40 ',' Unidad ',318 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 31X25 MM SDR-40 ',' Unidad ',318 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 50X25 MM SDR-40 ',' Unidad ',619 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 50X30 MM SDR-32,5 ',' Unidad ',687 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REDUCCIÓN PVC 50X31 MM SDR-32,5 ',' Unidad ',687 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA 1X2" C/C ',' m ',353 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA 1X2" S/C ',' m ',269 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA 1X3" S/C ',' m ',404 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA DE 1"X4" ',' m ',248 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA DE 2,5X20CM ',' m ',1227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA S/C 2,54X5CM L-C ',' m ',295 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA SEMIDURA 25X100 MM ',' Unidad ',539 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA SEMIDURA 25X75 MM ',' Unidad ',404 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REGLA SUAVE 25X50 MM ',' Unidad ',0 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REVESTIMIENTO (TRES MANOS) ',' m2 ',2719 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' REVESTIMIENTO PARA INTERIOR (10 LTS) ',' Unidad ',4661 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ROBO E INCENDIO ',' m2 ',828 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RODAPIE 1/2X3" ',' m ',376 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RODAPIE CON MOLDURA ',' ML ',569 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-113 (2 38MM) ',' Unidad ',14800 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-116 (1,58MM) ',' Unidad ',9349 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-313 (2 38MM) ',' Unidad ',18358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-316 (1,58MM) ',' Unidad ',11554 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-413 (2,38MM) ',' Unidad ',22638 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RT-416 (1 58MM) ',' Unidad ',13819 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SET BAÑO BEIGE 7 PZAS ',' Unidad ',5681 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SILLETA 100X12MM LISA PVC ',' Unidad ',3885 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SILLETA 100X18MM LISA PVC ',' Unidad ',3107 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SILLETA 75X12MM LISA PVC ',' Unidad ',4574 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SUBCONTRATO DE CORTE ',' m3 ',1243 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLA FORMALETA 1X12" ',' m ',1207 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA 1,2X7,5CM MACH ',' m ',150 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA 1/2*3" ',' m ',150 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA CORRIENTE 12X125 MM ',' Unidad ',336 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA CRISTOBAL 12X75 MM ',' Unidad ',725 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA LAUREL 12X125 MM ',' Unidad ',321 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA LAUREL 12X75 MM ',' Unidad ',269 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA NAZARENO 12X75 MM ',' Unidad ',258 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLILLA SEMIDURA 1ERA 12X175 MM ',' Unidad ',324 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLÓN ALMENDRO 12X2 PULG X 4 VARAS ',' Unidad ',17091 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TABLONCILLO SURÁ 1X3 ',' m ',462 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAN, S, GRASAS PREFA 1,8X1  4X1 8 ',' Unidad ',385857 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQ, AGUA PREFA 2 6X1  4X1 05 ',' Unidad ',445419 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQ, SEPT, PREFA 1,8X1 4X1,0 ',' Unidad ',284861 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE AGUA CALIENTE CAPACIDAD  150 LTS ',' Unidad ',105800 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO FIB VIDRIO 150 LTS WM12 ',' Unidad ',217530 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO FIB VIDRIO 450 LTS WM35 ',' Unidad ',559364 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO FIB VIDRIO 55 LTS WM4 ',' Unidad ',103586 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO METAL 135 LTS RJD36 ',' Unidad ',201992 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO METAL 450 LTS RJD119 ',' Unidad ',517930 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRO METAL 50 LTS RJH14 ',' Unidad ',108765 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE HIDRONEUMÁTICO (50 GLS) ',' Unidad ',258965 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE PARA AGUA (1000 LTS) ',' Unidad ',72510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TANQUE PARA ALMACENAMIENTO ',' Unidad ',72510 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 100MM HEMBRA PVC POTABLE ',' Unidad ',2425 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 12MM HEMBRA PVC POTABLE ',' Unidad ',71 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 150MM HEMBRA PVC POTABLE ',' Unidad ',6644 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 18MM HEMBRA PVC POTABLE ',' Unidad ',94 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 50MM HEMBRA PVC POTABLE ',' Unidad ',419 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPON 75MM HEMBRA PVC POTABLE ',' Unidad ',1379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPÓN LIMPIEZA PVC 100 MM ',' Unidad ',994 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPÓN LIMPIEZA PVC 75 MM ',' Unidad ',674 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE 100MM PVC ',' Unidad ',7203 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE 100MM PVC SANIT ',' Unidad ',5288 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE 100X100X75MM PVC ',' Unidad ',9559 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE 150X100MM PVC ',' Unidad ',24844 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE 75MM PVC ',' Unidad ',4551 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE CONCRETO 10 CM ',' Unidad ',2434 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEE CONCRETO D=15CM ',' Unidad ',3729 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA ESMALTADA 2 00 M/NO 26 ',' Unidad ',16573 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA ESMALTADA 2 10 M/NO 26 ',' Unidad ',11409 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA ESMALTADA 3 50 M/NO 26 ',' Unidad ',19016 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA MEDITERRANEO ',' m2 ',5101 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA SANTA FE CUMBRERA NATURAL ',' Unidad ',880 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA SANTA FE TIPO S NATURAL ',' Unidad ',880 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA TOLEDO ESMALTADA 1 09X0 70 NO 26 ',' Lámina ',2796 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA TOLEDO ESMALTADA 1 09X2 1 NO 26 ',' Lámina ',11409 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TEJA TOLEDO ESMALTADA 1 09X3 5 NO 26 ',' Lámina ',19016 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TERRACÍN ',' m2 ',5179 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TERRAZO ',' m2 ',4562 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TORNILLOS P/TECHO ',' Un ',20 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TRAMPA CON REGISTRO PVC 38 MM ',' Unidad ',4258 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TRAMPA PVC 100 MM ',' Unidad ',13179 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TRAMPA PVC 50 MM ',' Unidad ',1660 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TRAMPA PVC 75 MM ',' Unidad ',5735 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 17  100 MM ',' Unidad ',46095 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 17  75 MM ',' Unidad ',27968 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 26  50 MM ',' Unidad ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 32,5  100 MM ',' Unidad ',23306 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 32,5  75 MM ',' Unidad ',14502 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 41  100 MM ',' Unidad ',19163 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA JUNTA RÁPIDA  SDR 41  75 MM ',' Unidad ',11394 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA PARA DRENAJE  115 MM ',' Unidad ',8286 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  100 MM  SANIT Y PLUVIAL ',' Unidad ',20106 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  150 MM  SANIT Y PLUVIAL ',' Unidad ',48453 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  200 MM  SANIT Y PLUVIAL ',' Unidad ',138436 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  31 MM  SANIT Y PLUVIAL ',' Unidad ',3456 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  38 MM  SANIT Y PLUVIAL ',' Unidad ',3813 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  50 MM  SANIT Y PLUVIAL ',' Unidad ',5553 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  62 MM  SANIT Y PLUVIAL ',' Unidad ',10471 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 41  75 MM  SANIT Y PLUVIAL ',' Unidad ',12323 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBERÍA SDR 50  100 MM  SANIT Y PLUVIAL ',' Unidad ',16141 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO  CONCRETO PERFORADO 20 CM X 1 25 M ',' Unidad ',6215 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO 0,1X1,25M PERF CONC ',' Unidad ',2382 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO 25MMX6M H,G, LIVIAN ',' Unidad ',14109 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO ABASTO 12MM EMPOTRA ',' Unidad ',633 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO ABASTO PVC 1/2X1/2 LAVATORIO ',' Unidad ',633 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO ABASTO PVC 7/8X1/2 INODORO ',' Unidad ',633 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO ABASTO VINILO LAVATORIO 1/2X1/2 PULG ',' Unidad ',633 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 10CMX1,25M ',' Unidad ',1978 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 15CMX1,25M ',' Unidad ',2589 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 20CMX1,25M ',' Unidad ',4143 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 30CMX1,25M ',' Unidad ',9219 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 40CMX1,25M ',' Unidad ',14450 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 50CMX1,25M ',' Unidad ',20717 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 60CMX1,25 ',' Unidad ',25896 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 70CMX1,25M ',' Unidad ',31593 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 80CMX1,25 ',' Unidad ',36255 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-14 90 CMX1,25M ',' Unidad ',48685 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 100 CM X 2 50 M C-IV ',' Unidad ',356853 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 100 CM X 2 50 M C-V ',' Unidad ',385857 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 100X2,50M C-III ',' Unidad ',186454 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 107CMX2,50 C-III ',' Unidad ',186454 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 120 CM X 2 50 M C-IV ',' Unidad ',426256 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 120 CM X 2 50 M C-V ',' Unidad ',459921 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 120CMX2,50CM C-III ',' Unidad ',253267 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 152CMX2,00 C-III ',' Unidad ',198885 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 183CMX1,25 C-III ',' Unidad ',272949 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 213 CM X 1 25 M C-IV ',' Unidad ',494623 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 213 CM X 1 25 M C-V ',' Unidad ',647412 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 244 CM X 1 25 M C-IV ',' Unidad ',763946 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 244 CM X 1 25 M C-V ',' Unidad ',818329 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 40 CM X 1 25 M C-IV ',' Unidad ',33665 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 40 CM X 1 25 M C-V ',' Unidad ',47649 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 40 CM X 2 50 M C-IV ',' Unidad ',67330 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 40 CM X 2 50 M C-IV ',' Unidad ',67330 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 40 CM X 2 50 M C-V ',' Unidad ',95299 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 50 CM X 1 25 M C-IV ',' Unidad ',45059 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 50 CM X 1 25 M C-V ',' Unidad ',56972 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 50 CM X 2 50 M C-IV ',' Unidad ',90637 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 50 CM X 2 50 M C-V ',' Unidad ',113944 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 60CMX1,25 C-III ',' Unidad ',45577 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 70CMX1,25M C-III ',' Unidad ',51793 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 80CMX1,25 C-III ',' Unidad ',63705 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO C-76 90CMX1,25 C-III ',' Unidad ',82868 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO 350 MM X 1 00 M ',' Unidad ',3004 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO 375 MM X 1 00 M ',' Unidad ',3988 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO 450 MM X 1 00 M ',' Unidad ',4920 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO 525 MM X 1 00 M ',' Unidad ',6681 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO PERFORADO 10 CM X 1 25 M ',' Unidad ',880 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO PERFORADO 15 CM X 1 25 M ',' Unidad ',1087 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONCRETO PERFORADO 25 CM X 1 25 M ',' Unidad ',3004 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 12 MM X 3 M ',' Unidad ',671 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 18 MM X 3M ',' Unidad ',802 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 25 MM ',' Unidad ',1219 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 31 MM ',' Unidad ',1720 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 38 MM ',' Unidad ',2462 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO CONDUIT 50 MM ',' Unidad ',3863 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO EMT 31 MM X 3 M ',' Unidad ',4237 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SCH-40 12MM PVC ',' Unidad ',2812 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SCH-40 18MM PVC ',' Unidad ',4302 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-17 18MM ',' Unidad ',2364 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-17 19MM ',' Unidad ',2364 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-26 100MM PVC ',' Unidad ',32190 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-26 150MM PVC ',' Unidad ',73815 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-26 25MM PVC ',' Unidad ',2951 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-26 50MM PVC ',' Unidad ',9102 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-26 75MM PVC ',' Unidad ',19591 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-32,5 50MM ',' Unidad ',7233 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-32,5 75MM ',' Unidad ',15960 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-41,0 100MM ',' Unidad ',20106 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TUBO SDR-50,0 100MM ',' Unidad ',16141 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' UNION 50MM LISA PVC ',' Unidad ',538 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' UNION REPARACION PVC 100M ',' Unidad ',10358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' UNION REPARACION PVC 75M ',' Unidad ',6215 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VALVULA 100MM COMPUERTA ',' Unidad ',20717 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VALVULA 150MM COMPUERTA ',' Unidad ',124303 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VALVULA 200MM COMPUERTA ',' Unidad ',181275 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VALVULA 75MM COMPUERTA ',' Unidad ',10358 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VÁLVULA DE AIRE BVK  12 MM ',' Unidad ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA #2 (POR PESO) ',' Kgs ',441 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA #3 (POR PESO) ',' Kgs ',564 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA #4 (POR PESO) ',' Kgs ',561 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA #5 (POR PESO) ',' Kgs ',550 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA #6 (POR PESO) ',' Kgs ',561 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA COOPERWELL 150 CM X 12 MM C/GAZA ',' Unidad ',2109 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 2 LISA (6 MTS) ',' Unidad ',653 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 3 (6 MTS) ',' Unidad ',1878 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 3 LISA (6 MTS) ',' Unidad ',2299 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 4 (6 MTS) ',' Unidad ',3332 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 5 (6 MTS) ',' Unidad ',5095 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 6 (6 MTS) ',' Unidad ',7478 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 7 (6 MTS) ',' Unidad ',10180 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 8 (6 MTS) ',' Unidad ',13295 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VARILLA NO 9 (6 MTS) ',' Unidad ',16433 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VENTANA METALICA ',' m2 ',3055 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VERJA HIERRO COLOCADA ',' m2 ',12948 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDIO ACRILICO 91 X 1,83 ',' Lamina ',14880 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO ACRILICO 1,22 X 1,83 ',' Lamina ',17485 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO ACRILICO 75 X 1,83 ',' Lamina ',13114 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO POLARIZADO 1/8 ',' m2 ',15087 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO TRANSP, 1/8 ',' M2 ',6727 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO TRANSPARENTE 1/16 ',' m2 ',6417 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO TRANSPARENTE 1/8 ',' m2 ',4065 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIDRIO TRANSPARENTE ESCARCHADO ',' m2 ',5645 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOMA TELEFONICO ',' Unidad ',1843 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SALIDA TELEVISOR COAXIAL ',' Unidad ',3107 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' AGUARRAS ',' Litro ',870 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA DE BAÑO ',' Unidad ',38844 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PILA CONCRETO DOS BATEAS ',' Unidad ',11902 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVO DE ACERO 50 MM ',' Unidad ',11 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CLAVO PARA TECHO CON ARANDELA ',' Kg ',1219 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LIMAHOYA HG 26 45 X 1 83 ',' Unidad ',2522 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOPE PARA PUERTA ',' Unidad ',326 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LLAVIN DOBLE PASO ',' Unidad ',17077 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DRENAFLEX ',' metro ',1035 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DUCHA PARA BAÑO ',' Unidad ',54382 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN NO 2 AZUL ',' metro ',3431 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN NO 2 NEGRO ',' metro ',3431 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN NO 6 NEGRO ',' metro ',1356 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' INTERRUPTOR ENTRADA 3 POLOS ',' Unidad ',13125 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN NO 8 AZUL ',' metro ',840 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CENTRO DE CARGA 8 CIRCUITOS ',' Unidad ',15748 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BOMBILLO 75 WATTS ',' Unidad ',204 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE THHN NO 12 AZUL ',' metro ',322 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLAFON PORCELANA ',' Unidad ',393 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPE ELECTRICO 20 METROS ',' rollo ',0 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PASTILLA APAGADOR 3 VIAS ',' Unidad ',1420 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GAZA EMT TIPO AMERICANO 12 MM ',' Unidad ',14 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAJA CT 20-40 PARES ',' Unidad ',41434 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CABLE TELEFONICO 2 PARES ',' metro ',227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' LAMPARA FLUORESCENTE ',' Unidad ',25896 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PARA PAVIMENTO ',' m3 ',75099 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 70 KG/CM2 ',' m3 ',62151 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 105 KG/CM2 ',' m3 ',66295 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 140 KG/CM2 ',' m3 ',69920 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 225 KG/CM2 ',' m3 ',79243 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 245 KG/CM2 ',' m3 ',81832 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 280 KG/CM2 ',' m3 ',88048 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 315 KG/CM2 ',' m3 ',89601 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 350 KG/CM2 ',' m3 ',93227 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CONCRETO PREMEZCLADO 400 KG/CM2 ',' m3 ',98406 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MARMOLINA ',' Kg ',67 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MORTERO MAXIGLAS PARA VIDRIO ',' Unidad ',5179 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' OCRE AMARILLO ',' Kg ',1667 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PILOTE DE CONCRETO DIAMETRO 60 CM ',' metro ',13466 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' RETIRO DE ESCOMBROS ',' m3 ',2589 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SERVICIO BOMBEO TELESCOPICA ALCANCE 28 MTS ',' m3 ',8157 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SERVICIO BOMBEO TELESCOPICA ALCANCE 32 MTS ',' m3 ',10436 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOBA CEMENTO 10 KG/CM2 ',' m3 ',27859 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOBA CEMENTO 15 KG/CM2 ',' m3 ',30014 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOBA CEMENTO 25 KG/CM2 ',' m3 ',32080 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOBA CEMENTO 35 KG/CM2 ',' m3 ',34597 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TOBA CEMENTO 75 KG/CM2 ',' m3 ',45551 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' YESO ',' Kg ',471 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EXTINTOR 10 LIBRAS CLASE ABC ',' Unidad ',9291 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EXTINTOR 20 LIBRAS CLASE ABC ',' Unidad ',13336 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' EXTINTOR 30 LIBRAS CLASE ABC ',' Unidad ',16029 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' AGARRADERA TINA CROMADA ',' Unidad ',19303 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DESAGUE TINA AUTOMATICO ',' Unidad ',30100 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DUCHA LORENZETTI LORENDUXA ',' Unidad ',12347 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DUCHA LORENZETTI PARA LAVATORIO ',' Unidad ',19520 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DUCHA  MASAJE ',' Unidad ',11270 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' DUCHA TELEFONO PARA MASAJE ',' Unidad ',20147 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FLUXOMETRO ELECTRONICO ',' Unidad ',145020 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FLUXOMETRO PARA INODORO ',' Unidad ',77689 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' FLUXOMETRO PARA ORINAL ',' Unidad ',90637 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLE AEREO PARA COCINA ',' Unidad ',163147 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MUEBLE PARA FREGADERO ',' Unidad ',77689 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARENA RODADA DIAM MAX 10 MM ',' m3 ',6215 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARENA GRUESA BAJO 3/8 PULG ',' m3 ',5179 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' GRAVA DE 3/8 A 3/4 PULG ',' m3 ',3677 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARENA MORTERO ',' m3 ',7768 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ARENA POLVO DE ROCA ',' m3 ',4920 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CAL HIDRAULICA ',' S25 Kg ',1812 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESTUCO INTERIOR ',' Saco ',3004 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ESTUCO EXTERIOR ',' Saco ',3262 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MELAMINA 10 MM (1 83X2 5 M) ',' m2 ',4531 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' MELAMINA 16 MM (1 83X2 50 M) ',' m2 ',5101 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BARNIZ MARINO ',' Litro ',1165 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' BARNIZ HIDROREPELENTE ',' Litro ',1113 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLANCHA TERMOAISLANTE REVESTIDA 1000X2000X30 M ',' m2 ',1859 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PLANCHA TERMOAISLANTE POLIESTIRENO 1220X610X20 ',' m2 ',1973 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CUBREPISO TODO USO ',' m2 ',2341 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALFOMBRA PARA HOGAR U OFICINA ',' m2 ',7701 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ALFOMBRA RESIDENCIAL 14 MM ESPESOR ',' m2 ',13683 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' ADHESIVO PARA ALFOMBRAS ',' 18 Lit ',42786 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VINOLEUM ALTO TRAFICO ',' m2 ',14180 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' PUERTA ALUMINIO 2 HOJAS 1 8X2 5 MT ',' Unidad ',147610 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CRISTAL INCOLORO 2 00 MM ESPESOR ',' m2 ',3366 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CRISTAL INCOLORO 3 00 MM ESPESOR ',' m2 ',3656 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CRISTAL INCOLORO 10 0 MM ESPESOR ',' m2 ',12181 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' SAUNA EN CIPRES ',' m2 ',178685 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPIA BLOQUE SISADO (H=2 50 M) ',' ML ',35737 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' TAPIA BALDOSAS-COLUMNAS PREFA (H=2 0 M) ',' ML ',28486 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CERCA ALAMBRE 6 HILOS POSTE CONCRETO ',' ML ',3211 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNAS DE CONCRETO ',' m3 ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIGAS DE CONCRETO ',' m3 ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' COLUMNAS DE CONCRETO ',' m3 ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIGAS DE CONCRETO ',' m3 ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' VIGAS CONCRETO ',' m3 ',155379 ,0 )
 INSERT INTO [dbo].[Material]([Nombre],[Unidad],[PrecioUnitario], [Estado]) Values(' CORNIZA ',' ML ',2071 ,0 )
 GO

 Select * From Material