Select * From Cliente
Select * From DetalleFactura
Select * From Empleado
Select * From EmpleadoObra
Select * From Especialidad
Select * From Etapa
Select * From EtapaObra
Select * From Factura
Select * From Gasto
Select * From Ingeniero
Select * From Material
Select * From Obra
Select * From ObraMateriales
Select * From Ubicacion